apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: token-reviewer
rules:
- apiGroups: ["authentication.k8s.io"] # "" indicates the core API group
  resources: ["tokenreviews"]
  verbs: ["create"]