apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app/name: hello-world
  name: hello-world
spec:
  replicas: 1
  selector:
    matchLabels:
      app/name: hello-world
  template:
    metadata:
      labels:
        app/name: hello-world
      annotations:
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/agent-inject-secret-app: secret/data/hello-world
        vault.hashicorp.com/role: 'hello-world-app'
        vault.hashicorp.com/auth-path: 'auth/kubernetes'
        vault.hashicorp.com/log-level: 'trace'
    spec:
      serviceAccountName: hello-world
      containers:
      - image: gcr.io/google-samples/node-hello:1.0
        name: hello-world
        ports:
        - containerPort: 8080
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"